apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
      - name: stats-service
        image: zhaw-internship-stats_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: STATS_PORT
          value: "5001"
        - name: OTLP_ENDPOINT
          value: "jaeger:4317"
        - name: DEBUG
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  selector:
    app: stats-service
  ports:
  - port: 5001
    targetPort: 5001
